/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-06-28 10:16:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>javascript ajax</title>\r\n");
      out.write("<!-- 반응형 웹 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("<!-- 파비콘 -->\r\n");
      out.write("<link rel=\"icon\" href=\"./images/ic_file.gif\">\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.css\">\r\n");
      out.write("<!-- jQury -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery-3.7.0.js\"></script>\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/bootstrap.js\"></script>\r\n");
      out.write("<!-- ajax 구현 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/ajax.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 회원 가입 양식 -->\r\n");
      out.write("<div class=\"container\" style=\"margin-top: 20px;\">\r\n");
      out.write("	<table class=\"table\">\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr class=\"success\">\r\n");
      out.write("				<th colspan=\"2\" style=\"text-align: center; font-size: 25px;\">회원가입</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th style=\"background-color: pink; vertical-align: middle;\">이름</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input \r\n");
      out.write("						id=\"name\" \r\n");
      out.write("						class=\"form-control\"\r\n");
      out.write("						type=\"text\"\r\n");
      out.write("						autocomplete=\"off\"\r\n");
      out.write("						placeholder=\"이름을 입력하세요.\"\r\n");
      out.write("					/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th style=\"background-color: tomato; vertical-align: middle;\">나이</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input \r\n");
      out.write("						id=\"age\" \r\n");
      out.write("						class=\"form-control\"\r\n");
      out.write("						type=\"text\"\r\n");
      out.write("						autocomplete=\"off\"\r\n");
      out.write("						placeholder=\"나이를 입력하세요.\"\r\n");
      out.write("					/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th style=\"background-color: dodgerblue; vertical-align: middle;\">성별</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"form-group\" style=\"text-align: center; margin: 0px auto\">\r\n");
      out.write("						<div class=\"btn-group\" data-toggle=\"buttons\">\r\n");
      out.write("							<label class=\"btn btn-primary\">\r\n");
      out.write("								<input \r\n");
      out.write("									type=\"radio\" \r\n");
      out.write("									name=\"gender\" \r\n");
      out.write("									value=\"남자\"\r\n");
      out.write("								/>남자\r\n");
      out.write("							</label>\r\n");
      out.write("							<label class=\"btn btn-primary active\">\r\n");
      out.write("								<input \r\n");
      out.write("									type=\"radio\" \r\n");
      out.write("									name=\"gender\" \r\n");
      out.write("									value=\"여자\"\r\n");
      out.write("									checked=\"checked\"\r\n");
      out.write("								/>여자\r\n");
      out.write("							</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th style=\"background-color: yellowgreen; vertical-align: middle;\">이메일</th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input \r\n");
      out.write("						id=\"email\" \r\n");
      out.write("						class=\"form-control\"\r\n");
      out.write("						type=\"text\"\r\n");
      out.write("						autocomplete=\"off\"\r\n");
      out.write("						placeholder=\"이메일을 입력하세요.\"\r\n");
      out.write("					/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr class=\"warning\">\r\n");
      out.write("				<td colspan=\"2\">\r\n");
      out.write("					<input \r\n");
      out.write("						class=\"btn btn-danger pull-right\" \r\n");
      out.write("						type=\"button\" \r\n");
      out.write("						value=\"입력하기\"\r\n");
      out.write("						onclick=\"insertFunction()\"\r\n");
      out.write("					/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 회원 출력 양식 -->\r\n");
      out.write("<!-- 검색어 입력 -->\r\n");
      out.write("<div class=\"container\" style=\"margin-top: 20px;\">\r\n");
      out.write("	<div class=\"form-group row pull-right\"> <!-- row 12 -->\r\n");
      out.write("		<div class=\"col-xs-8\">\r\n");
      out.write("			<input \r\n");
      out.write("				id=\"username\" \r\n");
      out.write("				class=\"form-control\" \r\n");
      out.write("				type=\"text\" \r\n");
      out.write("				size=\"20\" \r\n");
      out.write("				onkeyup=\"searchFunction()\"\r\n");
      out.write("				autocomplete=\"off\" \r\n");
      out.write("			/> <!-- 자동완성 기능 지원x -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-xs-2\">\r\n");
      out.write("			<input \r\n");
      out.write("				class=\"btn btn-primary\" \r\n");
      out.write("				type=\"button\" \r\n");
      out.write("				value=\"검색\" \r\n");
      out.write("				onclick=\"searchFunction()\"\r\n");
      out.write("			/>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 검색 결과 출력 -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<table class=\"table table-hover\"><!-- table-hover 마우스 커서 올라갈 때 색 변경 -->\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr class=\"info\">\r\n");
      out.write("				<th style=\"text-align: center;\">번호</th>\r\n");
      out.write("				<th style=\"text-align: center;\">이름</th>\r\n");
      out.write("				<th style=\"text-align: center;\">나이</th>\r\n");
      out.write("				<th style=\"text-align: center;\">성별</th>\r\n");
      out.write("				<th style=\"text-align: center;\">이메일</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody id=\"ajaxTable\">\r\n");
      out.write("			<tr></tr>\r\n");
      out.write("		</tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
