/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-06-27 03:41:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>jQuery ajax</title>\r\n");
      out.write("<!-- 반응형 웹 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("<!-- 파비콘 -->\r\n");
      out.write("<link rel=\"icon\" href=\"./images/ic_file.gif\">\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.css\">\r\n");
      out.write("<!-- jQury -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery-3.7.0.js\"></script>\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/bootstrap.js\"></script>\r\n");
      out.write("<!-- ajax 구현 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/ajax.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 회원 가입 양식 -->\r\n");
      out.write("<div class=\"container\" style=\"margin-top: 20px;\">\r\n");
      out.write("	<!-- <form action=\"./UserRegisger\" method=\"post\"> --><!-- ① -->\r\n");
      out.write("	<form> <!-- ② -->\r\n");
      out.write("		<table class=\"table table-hover table-bordered\" style=\"border: 1px solid #FF0000\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr class=\"success\">\r\n");
      out.write("					<th colspan=\"3\" style=\"text-align: center;\">\r\n");
      out.write("						<h2>회원 가입 양식</h2>\r\n");
      out.write("					</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"danger\" style=\"vertical-align: middle; width: 120px;\">아이디</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input \r\n");
      out.write("							id=\"userID\" \r\n");
      out.write("							class=\"form-control\" \r\n");
      out.write("							type=\"text\" \r\n");
      out.write("							name=\"userID\"\r\n");
      out.write("							placeholder=\"아이디를 입력하세요.\"\r\n");
      out.write("							autocomplete=\"off\"\r\n");
      out.write("						/>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td class=\"info\" \r\n");
      out.write("						style=\"vertical-align: middle; width: 120px; text-align: center;\">\r\n");
      out.write("						<button \r\n");
      out.write("							class=\"btn btn-primary\" \r\n");
      out.write("							type=\"button\" \r\n");
      out.write("							onclick=\"registerCheckFunction()\">\r\n");
      out.write("							중복검사\r\n");
      out.write("						</button>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"danger\" style=\"vertical-align: middle;\">비밀번호</th>\r\n");
      out.write("					<td colspan=\"2\">\r\n");
      out.write("						<input \r\n");
      out.write("							id=\"userPassword1\" \r\n");
      out.write("							class=\"form-control\" \r\n");
      out.write("							type=\"password\" \r\n");
      out.write("							name=\"userPassword1\"\r\n");
      out.write("							placeholder=\"비밀번호를 입력하세요.\"\r\n");
      out.write("							autocomplete=\"off\"\r\n");
      out.write("							onkeyup=\"passwordCheckFunction()\"\r\n");
      out.write("						/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"danger\" style=\"vertical-align: middle;\">비밀번호 확인</th>\r\n");
      out.write("					<td colspan=\"2\">\r\n");
      out.write("						<input \r\n");
      out.write("							id=\"userPassword2\" \r\n");
      out.write("							class=\"form-control\" \r\n");
      out.write("							type=\"password\" \r\n");
      out.write("							name=\"userPassword2\"\r\n");
      out.write("							placeholder=\"비밀번호를 입력하세요.\"\r\n");
      out.write("							autocomplete=\"off\"\r\n");
      out.write("							onkeyup=\"passwordCheckFunction()\"\r\n");
      out.write("						/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"danger\" style=\"vertical-align: middle;\">이름</th>\r\n");
      out.write("					<td colspan=\"2\">\r\n");
      out.write("						<input \r\n");
      out.write("							id=\"userName\" \r\n");
      out.write("							class=\"form-control\" \r\n");
      out.write("							type=\"text\" \r\n");
      out.write("							name=\"userName\"\r\n");
      out.write("							placeholder=\"이름을 입력하세요.\"\r\n");
      out.write("							autocomplete=\"off\"\r\n");
      out.write("						/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"danger\" style=\"vertical-align: middle;\">나이</th>\r\n");
      out.write("					<td colspan=\"2\">\r\n");
      out.write("						<input \r\n");
      out.write("							id=\"userAge\" \r\n");
      out.write("							class=\"form-control\" \r\n");
      out.write("							type=\"text\" \r\n");
      out.write("							name=\"userAge\"\r\n");
      out.write("							placeholder=\"나이를 입력하세요.\"\r\n");
      out.write("							autocomplete=\"off\"\r\n");
      out.write("						/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"danger\" style=\"vertical-align: middle;\">성별</th>\r\n");
      out.write("					<td colspan=\"2\">\r\n");
      out.write("						<div class=\"form-group\" style=\"text-align: center; margin: 0px auto\">\r\n");
      out.write("							<div class=\"btn-group\" data-toggle=\"buttons\">\r\n");
      out.write("								<label class=\"btn btn-primary\">\r\n");
      out.write("									<input \r\n");
      out.write("										type=\"radio\" \r\n");
      out.write("										name=\"userGender\" \r\n");
      out.write("										value=\"남자\"\r\n");
      out.write("									/>남자\r\n");
      out.write("								</label>\r\n");
      out.write("								<label class=\"btn btn-primary active\">\r\n");
      out.write("									<input \r\n");
      out.write("										type=\"radio\" \r\n");
      out.write("										name=\"userGender\" \r\n");
      out.write("										value=\"여자\"\r\n");
      out.write("										checked=\"checked\"\r\n");
      out.write("									/>여자\r\n");
      out.write("								</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"danger\" style=\"vertical-align: middle;\">이메일</th>\r\n");
      out.write("					<td colspan=\"2\">\r\n");
      out.write("						<input \r\n");
      out.write("							id=\"userEmail\" \r\n");
      out.write("							class=\"form-control\" \r\n");
      out.write("							type=\"email\" \r\n");
      out.write("							name=\"userEmail\"\r\n");
      out.write("							placeholder=\"이메일을 입력하세요.\"\r\n");
      out.write("							autocomplete=\"off\"\r\n");
      out.write("						/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"3\" style=\"text-align: center;\">\r\n");
      out.write("						<!-- 비밀번호 일치 검사 결과 메시지가 출력될 영역 -->\r\n");
      out.write("						<h5 id=\"passwordCheckMessage\" style=\"color: red; font-weight: bold;\"></h5>\r\n");
      out.write("						<!-- 아이디 중복 검사 결과 메시지가 출력될 영역 -->\r\n");
      out.write("						<h5 id=\"idCheckMessage\" style=\"color: red; font-weight: bold;\"></h5>\r\n");
      out.write("						<!-- 오류 메시지가 출력될 영역 -->\r\n");
      out.write("						<h5 id=\"errorMessage\" style=\"color: blue; font-weight: bold;\">\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("						</h5>\r\n");
      out.write("						<!-- <input class=\"btn btn-primary\" type=\"submit\" value=\"회원가입\"> --> <!-- ① -->	\r\n");
      out.write("						<input class=\"btn btn-primary\" type=\"button\" value=\"회원가입\"\r\n");
      out.write("							onclick=\"userRegister()\"/> <!-- ② -->				\r\n");
      out.write("						<input class=\"btn btn-primary\" type=\"reset\" value=\"다시쓰기\">					\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("	현재 프로젝트는 session을 사용하지 않기 때문에 k20230626_1_register에서 사용하던 모든 \r\n");
      out.write("	스크립트릿을 삭제한다.  \r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 회원 저장 모달 창 -->\r\n");
      out.write("<div id=\"messageModal\" class=\"modal fade\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("	<div class=\"vertical-alignment-helper\">\r\n");
      out.write("		<div class=\"modal-dialog vertical-align-center\">\r\n");
      out.write("			<!-- 모달 창의 종류를 설정한다. -->\r\n");
      out.write("			<!-- messageCheck라는 id를 추가하고 class를 제거한다. -->\r\n");
      out.write("			<div id=\"messageCheck\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<!-- 헤더 -->\r\n");
      out.write("				<div class=\"modal-header panel-heading\">\r\n");
      out.write("					<!-- 헤더 오른쪽 상단에 \"X\" 버튼 표시 -->\r\n");
      out.write("					<button class=\"close\" type=\"button\" data-dismiss=\"modal\">\r\n");
      out.write("						<span aria-hidden=\"ture\">&times;</span>\r\n");
      out.write("						<span class=\"sr-only\">Close</span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<!-- messageType이라는 id를 추가한다. -->\r\n");
      out.write("					<h4 id=\"messageType\" class=\"modal-title\">\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("					</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<!-- 바디 -->\r\n");
      out.write("				<!-- messageContent이라는 id를 추가한다. -->\r\n");
      out.write("				<div id=\"messageContent\" class=\"modal-body\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<!-- 풋터 -->\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button class=\"btn btn-primary\" type=\"button\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 이게 들어가야 모달창이 뜬다. 그리고 모달 밑에 있어야 한다. -->\r\n");
      out.write("<!-- \r\n");
      out.write("모달 창을 띄우는 기능을 실행하는 스트립트를 ajax.js로 옴긴다.\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$('#messageModal').modal('show');\r\n");
      out.write("</script> \r\n");
      out.write("-->	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
